/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        LiberaBrillianceGdxClass.cpp
//
// description : C++ source for the LiberaBrillianceGdxClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the LiberaBrillianceGdx once per process.
//
// project :     Libera BPM Event Receiver Device Server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <LiberaBrillianceGdxClass.h>

/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass.cpp

//-------------------------------------------------------------------
/**
 *	Create LiberaBrillianceGdxClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_LiberaBrillianceGdx_class(const char *name) {
		return LiberaBrillianceGdx_ns::LiberaBrillianceGdxClass::init(name);
	}
}

namespace LiberaBrillianceGdx_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
LiberaBrillianceGdxClass *LiberaBrillianceGdxClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		LiberaBrillianceGdxClass::LiberaBrillianceGdxClass(string &s)
 * description : 	constructor for the LiberaBrillianceGdxClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
LiberaBrillianceGdxClass::LiberaBrillianceGdxClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering LiberaBrillianceGdxClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::constructor

	cout2 << "Leaving LiberaBrillianceGdxClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		LiberaBrillianceGdxClass::~LiberaBrillianceGdxClass()
 * description : 	destructor for the LiberaBrillianceGdxClass
 */
//--------------------------------------------------------
LiberaBrillianceGdxClass::~LiberaBrillianceGdxClass()
{
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		LiberaBrillianceGdxClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
LiberaBrillianceGdxClass *LiberaBrillianceGdxClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new LiberaBrillianceGdxClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		LiberaBrillianceGdxClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
LiberaBrillianceGdxClass *LiberaBrillianceGdxClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		GetParametersClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetParametersClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "GetParametersClass::execute(): arrived" << endl;
	return insert((static_cast<LiberaBrillianceGdx *>(device))->get_parameters());
}

//--------------------------------------------------------
/**
 * method : 		ReloadSystemPropertiesClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReloadSystemPropertiesClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ReloadSystemPropertiesClass::execute(): arrived" << endl;
	((static_cast<LiberaBrillianceGdx *>(device))->reload_system_properties());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		MagicCommandClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *MagicCommandClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "MagicCommandClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<LiberaBrillianceGdx *>(device))->magic_command(argin));
}

//--------------------------------------------------------
/**
 * method : 		ForceInitSettingsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ForceInitSettingsClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ForceInitSettingsClass::execute(): arrived" << endl;
	((static_cast<LiberaBrillianceGdx *>(device))->force_init_settings());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetTraceLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetTraceLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetTraceLevelClass::execute(): arrived" << endl;
	Tango::DevUShort argin;
	extract(in_any, argin);
	((static_cast<LiberaBrillianceGdx *>(device))->set_trace_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetStatusInterlockClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetStatusInterlockClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetStatusInterlockClass::execute(): arrived" << endl;
	((static_cast<LiberaBrillianceGdx *>(device))->reset_status_interlock());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum LiberaBrillianceGdxClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum LiberaBrillianceGdxClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum LiberaBrillianceGdxClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::get_class_property()
 *	Description : Read database to initialize class property data members.
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::get_class_property()
{
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::get_class_property_before) ENABLED START -----*/
	
	//	Initialize class property data members
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::get_class_property_before
	//	Read class properties from database.
	cl_prop.push_back(Tango::DbDatum("Institute"));
	
	//	Call database and extract values
	if (Tango::Util::instance()->_UseDb==true)
		get_db_class()->get_property(cl_prop);
	Tango::DbDatum	def_prop;
	int	i = -1;

	//	Try to extract Institute value
	if (cl_prop[++i].is_empty()==false)	cl_prop[i]  >>  institute;
	else
	{
		//	Check default value for Institute
		def_prop = get_default_class_property(cl_prop[i].name);
		if (def_prop.is_empty()==false)
		{
			def_prop    >>  institute;
			cl_prop[i]  <<  institute;
		}
	}
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::get_class_property_after) ENABLED START -----*/
	
	//	Check class property data members init
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::get_class_property_after

}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties
	prop_name = "Institute";
	prop_desc = "0: TANGO_INSTITUTE (GENERIC)\n1: ALBA\n2: ESRF\n3: ELETTRA\n4: SOLEIL";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		cl_def_prop.push_back(data);
		add_wiz_class_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_class_prop(prop_name, prop_desc);

	//	Set Default device Properties
	prop_name = "LiberaIpAddr";
	prop_desc = "The Libera IP address [no default value]";
	prop_def  = "127.0.0.1";
	vect_data.clear();
	vect_data.push_back("127.0.0.1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ErrorTrace";
	prop_desc = "Trace Error functionality for the Libera, by default is Disabled:\n * Value: OutPut ,  TraceLevel\n	* Output[0] :  OutPut on Screen = 0\n	                         OutPut on File = 0 (﻿/var/tmp/ds.log/LiberaMciTrace.log)\n	* TraceLevel[1] : ﻿   Off     = 0,\n        		      Low     = 1,\n		      Med     = 2,\n		      High    = 3,\n		      Detail  = 4";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Libera GDX Device Server");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Libera GDX Device Server");
	str_desc.push_back("The interface should be the same as for the Brillance model.");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("LiberaBrillianceGdx");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new LiberaBrillianceGdx(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		LiberaBrillianceGdx *dev = static_cast<LiberaBrillianceGdx *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::attribute_factory_before
	//	Attribute : FOFBInterlockStatus
	FOFBInterlockStatusAttrib	*fofbinterlockstatus = new FOFBInterlockStatusAttrib();
	Tango::UserDefaultAttrProp	fofbinterlockstatus_prop;
	fofbinterlockstatus_prop.set_description("FOFB Interlock Status\nnode:boards.gdx1.fofb.interlock.status");
	fofbinterlockstatus_prop.set_label("Interlock Status");
	//	unit	not set for FOFBInterlockStatus
	//	standard_unit	not set for FOFBInterlockStatus
	//	display_unit	not set for FOFBInterlockStatus
	//	format	not set for FOFBInterlockStatus
	//	max_value	not set for FOFBInterlockStatus
	//	min_value	not set for FOFBInterlockStatus
	//	max_alarm	not set for FOFBInterlockStatus
	//	min_alarm	not set for FOFBInterlockStatus
	//	max_warning	not set for FOFBInterlockStatus
	//	min_warning	not set for FOFBInterlockStatus
	//	delta_t	not set for FOFBInterlockStatus
	//	delta_val	not set for FOFBInterlockStatus
	
	fofbinterlockstatus->set_default_properties(fofbinterlockstatus_prop);
	//	Not Polled
	fofbinterlockstatus->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(fofbinterlockstatus);

	//	Attribute : GbeOrbitEnable
	GbeOrbitEnableAttrib	*gbeorbitenable = new GbeOrbitEnableAttrib();
	Tango::UserDefaultAttrProp	gbeorbitenable_prop;
	gbeorbitenable_prop.set_description("Gbe Orbit Enabled\nnode:boards.gdx1.gbe_orbit.enable");
	gbeorbitenable_prop.set_label("Gbe Orbit Enabled");
	//	unit	not set for GbeOrbitEnable
	//	standard_unit	not set for GbeOrbitEnable
	//	display_unit	not set for GbeOrbitEnable
	//	format	not set for GbeOrbitEnable
	//	max_value	not set for GbeOrbitEnable
	//	min_value	not set for GbeOrbitEnable
	//	max_alarm	not set for GbeOrbitEnable
	//	min_alarm	not set for GbeOrbitEnable
	//	max_warning	not set for GbeOrbitEnable
	//	min_warning	not set for GbeOrbitEnable
	//	delta_t	not set for GbeOrbitEnable
	//	delta_val	not set for GbeOrbitEnable
	
	gbeorbitenable->set_default_properties(gbeorbitenable_prop);
	//	Not Polled
	gbeorbitenable->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gbeorbitenable);

	//	Attribute : FOFBStateMode
	FOFBStateModeAttrib	*fofbstatemode = new FOFBStateModeAttrib();
	Tango::UserDefaultAttrProp	fofbstatemode_prop;
	fofbstatemode_prop.set_description("FOFB State Mode\nnode:boards.gdx1.fofb.state.mode");
	fofbstatemode_prop.set_label("State Mode");
	fofbstatemode_prop.set_unit("Enumeration (off,on,standby)");
	//	standard_unit	not set for FOFBStateMode
	//	display_unit	not set for FOFBStateMode
	//	format	not set for FOFBStateMode
	//	max_value	not set for FOFBStateMode
	//	min_value	not set for FOFBStateMode
	//	max_alarm	not set for FOFBStateMode
	//	min_alarm	not set for FOFBStateMode
	//	max_warning	not set for FOFBStateMode
	//	min_warning	not set for FOFBStateMode
	//	delta_t	not set for FOFBStateMode
	//	delta_val	not set for FOFBStateMode
	
	fofbstatemode->set_default_properties(fofbstatemode_prop);
	//	Not Polled
	fofbstatemode->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(fofbstatemode);

	//	Attribute : FOFBSwitch
	FOFBSwitchAttrib	*fofbswitch = new FOFBSwitchAttrib();
	Tango::UserDefaultAttrProp	fofbswitch_prop;
	fofbswitch_prop.set_description("FOFB Switch\nnode:boards.gdx1.fofb.switch");
	fofbswitch_prop.set_label("Switch");
	fofbswitch_prop.set_unit("Enumeration (off,on,hw)");
	//	standard_unit	not set for FOFBSwitch
	//	display_unit	not set for FOFBSwitch
	//	format	not set for FOFBSwitch
	//	max_value	not set for FOFBSwitch
	//	min_value	not set for FOFBSwitch
	//	max_alarm	not set for FOFBSwitch
	//	min_alarm	not set for FOFBSwitch
	//	max_warning	not set for FOFBSwitch
	//	min_warning	not set for FOFBSwitch
	//	delta_t	not set for FOFBSwitch
	//	delta_val	not set for FOFBSwitch
	
	fofbswitch->set_default_properties(fofbswitch_prop);
	//	Not Polled
	fofbswitch->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(fofbswitch);

	//	Attribute : FOFBAxis
	FOFBAxisAttrib	*fofbaxis = new FOFBAxisAttrib();
	Tango::UserDefaultAttrProp	fofbaxis_prop;
	fofbaxis_prop.set_description("FOFB Axis\nnode:boards.gdx1.fofb.axis");
	fofbaxis_prop.set_label("Axis");
	fofbaxis_prop.set_unit("Enumeration (x,y)");
	//	standard_unit	not set for FOFBAxis
	//	display_unit	not set for FOFBAxis
	//	format	not set for FOFBAxis
	//	max_value	not set for FOFBAxis
	//	min_value	not set for FOFBAxis
	//	max_alarm	not set for FOFBAxis
	//	min_alarm	not set for FOFBAxis
	//	max_warning	not set for FOFBAxis
	//	min_warning	not set for FOFBAxis
	//	delta_t	not set for FOFBAxis
	//	delta_val	not set for FOFBAxis
	
	fofbaxis->set_default_properties(fofbaxis_prop);
	//	Not Polled
	fofbaxis->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(fofbaxis);

	//	Attribute : FOFBDimBpms
	FOFBDimBpmsAttrib	*fofbdimbpms = new FOFBDimBpmsAttrib();
	Tango::UserDefaultAttrProp	fofbdimbpms_prop;
	fofbdimbpms_prop.set_description("FOFB Dim BPMS\nnode:boards.gdx1.dim.bpms");
	fofbdimbpms_prop.set_label("Dim BPMS");
	//	unit	not set for FOFBDimBpms
	//	standard_unit	not set for FOFBDimBpms
	//	display_unit	not set for FOFBDimBpms
	//	format	not set for FOFBDimBpms
	//	max_value	not set for FOFBDimBpms
	//	min_value	not set for FOFBDimBpms
	//	max_alarm	not set for FOFBDimBpms
	//	min_alarm	not set for FOFBDimBpms
	//	max_warning	not set for FOFBDimBpms
	//	min_warning	not set for FOFBDimBpms
	//	delta_t	not set for FOFBDimBpms
	//	delta_val	not set for FOFBDimBpms
	
	fofbdimbpms->set_default_properties(fofbdimbpms_prop);
	//	Not Polled
	fofbdimbpms->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(fofbdimbpms);

	//	Attribute : FOFBDimEigenmodes
	FOFBDimEigenmodesAttrib	*fofbdimeigenmodes = new FOFBDimEigenmodesAttrib();
	Tango::UserDefaultAttrProp	fofbdimeigenmodes_prop;
	fofbdimeigenmodes_prop.set_description("FOFB Dim Eigenmodes\nnode:boards.gdx1.fofb.dim.eigenmodes");
	fofbdimeigenmodes_prop.set_label("Dim Eigenmodes");
	//	unit	not set for FOFBDimEigenmodes
	//	standard_unit	not set for FOFBDimEigenmodes
	//	display_unit	not set for FOFBDimEigenmodes
	//	format	not set for FOFBDimEigenmodes
	fofbdimeigenmodes_prop.set_max_value("88");
	fofbdimeigenmodes_prop.set_min_value("0");
	//	max_alarm	not set for FOFBDimEigenmodes
	//	min_alarm	not set for FOFBDimEigenmodes
	//	max_warning	not set for FOFBDimEigenmodes
	//	min_warning	not set for FOFBDimEigenmodes
	//	delta_t	not set for FOFBDimEigenmodes
	//	delta_val	not set for FOFBDimEigenmodes
	
	fofbdimeigenmodes->set_default_properties(fofbdimeigenmodes_prop);
	//	Not Polled
	fofbdimeigenmodes->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(fofbdimeigenmodes);

	//	Attribute : GbeOrbitStatus
	GbeOrbitStatusAttrib	*gbeorbitstatus = new GbeOrbitStatusAttrib();
	Tango::UserDefaultAttrProp	gbeorbitstatus_prop;
	gbeorbitstatus_prop.set_description("Gbe Orbit Status\nnode:boards.gdx1.gbe_orbit.status");
	gbeorbitstatus_prop.set_label("Gbe Status");
	//	unit	not set for GbeOrbitStatus
	//	standard_unit	not set for GbeOrbitStatus
	//	display_unit	not set for GbeOrbitStatus
	//	format	not set for GbeOrbitStatus
	//	max_value	not set for GbeOrbitStatus
	//	min_value	not set for GbeOrbitStatus
	//	max_alarm	not set for GbeOrbitStatus
	//	min_alarm	not set for GbeOrbitStatus
	//	max_warning	not set for GbeOrbitStatus
	//	min_warning	not set for GbeOrbitStatus
	//	delta_t	not set for GbeOrbitStatus
	//	delta_val	not set for GbeOrbitStatus
	
	gbeorbitstatus->set_default_properties(gbeorbitstatus_prop);
	//	Not Polled
	gbeorbitstatus->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gbeorbitstatus);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::pipe_factory_before
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::command_factory()
{
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::command_factory_before


	//	Command GetParameters
	GetParametersClass	*pGetParametersCmd =
		new GetParametersClass("GetParameters",
			Tango::DEV_VOID, Tango::DEVVAR_DOUBLESTRINGARRAY,
			"N/A",
			"The BPM gain and offsets",
			Tango::OPERATOR);
	command_list.push_back(pGetParametersCmd);

	//	Command ReloadSystemProperties
	ReloadSystemPropertiesClass	*pReloadSystemPropertiesCmd =
		new ReloadSystemPropertiesClass("ReloadSystemProperties",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"n/a",
			"n/a",
			Tango::OPERATOR);
	command_list.push_back(pReloadSystemPropertiesCmd);

	//	Command MagicCommand
	MagicCommandClass	*pMagicCommandCmd =
		new MagicCommandClass("MagicCommand",
			Tango::DEV_STRING, Tango::DEVVAR_STRINGARRAY,
			"absolute path of the node name",
			"value of specified node(s)",
			Tango::EXPERT);
	command_list.push_back(pMagicCommandCmd);

	//	Command ForceInitSettings
	ForceInitSettingsClass	*pForceInitSettingsCmd =
		new ForceInitSettingsClass("ForceInitSettings",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"n/a",
			"n/a",
			Tango::OPERATOR);
	command_list.push_back(pForceInitSettingsCmd);

	//	Command SetTraceLevel
	SetTraceLevelClass	*pSetTraceLevelCmd =
		new SetTraceLevelClass("SetTraceLevel",
			Tango::DEV_USHORT, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetTraceLevelCmd);

	//	Command ResetStatusInterlock
	ResetStatusInterlockClass	*pResetStatusInterlockCmd =
		new ResetStatusInterlockClass("ResetStatusInterlock",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetStatusInterlockCmd);

	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		LiberaBrillianceGdxClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		LiberaBrillianceGdxClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void LiberaBrillianceGdxClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		LiberaBrillianceGdx *dev = static_cast<LiberaBrillianceGdx *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrillianceGdxClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *LiberaBrillianceGdxClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(LiberaBrillianceGdxClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	LiberaBrillianceGdxClass::Additional Methods
} //	namespace
